---
title: "Desmitais uzdevums: novērojumu atlase modelēšanai"
output: rmarkdown::github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Termiņš

Līdz ~~(2025-01-20)~~ ~~(2025-02-17)~~  ~~(2025-02-24)~~ **2025-03-03** projekta *sharepoint* 
direktorijā "WP2_macibas" savā apakšdirektorijā iesniedziet 
devitajā uzdevumā izvēlēto sugu novērojumus, kas atbilstoši projekta vajadzībām sagatavoti modelēšanai.

## Premise

Šī repozitorija pamata aprakstā ieteiktajā literatūrā, kas papildināta ar 
aktuālajām publikācijām, iepazīstieties ar galvenajiem konceptiem un pieejām sugu 
izplatības un plašākā kontekstā - ekoloģiskajā modelēšanā. Mēģiniet noskaidrot, kādas 
ir biežāk lietotās datu analīzes metodes un pieejas sugu izplatības modelēšanā, kādi 
dati tām ir nepieciešami. Saprotiet, ka ļoti svarīgas ir pietiekoši precīzi datētas un 
ģeoreferencētas drošas klātbūtnes vietas, kuras spēj raksturot (vai vismaz tiecās 
uz šo spēju) interesējošās sugas interesējošās dzīves stadijas ekoloģisko nišu. 



## Uzdevums

Pildot uzdevumu, domājiet arī par devīto un vienpadsmito uzdevumiem.

1. Iepazīstieties ar projekta sanāksmju materiāliem (direktorija "Sanaksmes"), ja 
tajās nepiedalījāties, un direktorijā "WP1" esošajiem uzdevumu (Task1.1, Task1.2 
un Task1.3) aprakstiem un sniegtajiem piemēriem.

2. Sevis devītajā uzdevumā izvēlētajām sugām veiciet pilnu darba gaitu novērojumu 
apkopošanai un izvēlei modelēšanai, nodrošinot izsekojamību, atkārtojamību, reproducējamību 
un replicējamību.

## Padomi

Jau kopš devītā uzdevuma uzsvērti mācamies arī strādāt kā komanda. Sazināmies, pārrunājam 
problēmas, nepieciešamības un iespējamos risinājumus, izmantojot diskusiju 
forumu vai tiekoties.