---
title: "Devītais uzdevums: sugu izvēle un to aprakstu (modelēšanai un aizsardzības telpiskajai plānošanai) sagatavošana"
output: rmarkdown::github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Termiņš

Līdz ~~(2025-01-20)~~ ~~(2025-02-17)~~  ~~(2025-02-24)~~ **2025-03-03** projekta *sharepoint* 
direktorijā "WP2_macibas" izveidojiet savu apakšdirektoriju, kurā iesniedziet 
vismaz 10 sugu aprakstus.

## Premise

Šo uzdevumu mērķis ir sīkiem soļiem būvēt izpratni, lai ieskatītos dažādos aspektos, 
kurus ir nepieciešams ņemt vērā, lai sagatavotos un veiktu sugu izplatības modelēšanu. 
Statistisko modeļu piemērošana ekoloģijā ir veicama ar izpratni gan par bioloģijas 
mehāniskiem, gan statistiskajiem rīkiem, kuru izvēle ir pielāgojama pētāmajam jautājumam 
un datu īpašībām. Tajā pašā laikā, datus ir jāievāc/jāiegūst tādus un jāorganizē tā, lai 
interesējošās datu analīzes būtu iespējams pielietot bez nozīmīgas pārkāpumu pret 
priekšnosacījumiem ietekmes. Tas nozīmē, ka ir jābūt vismaz pamata izpratnei par 
datu "rašanās" procesu, kuru izmēģināsim šajā un dažos nākošajos uzdevumos.

Atgādinājumam, viens no projekta uzdevumiem ir radīt pielietojamas zināšanas 
bioloģiskās daudzveidības apsaimniekošanā un tās plānošanā. Tātad, projektā modelējamām 
sugām ir jābūt tādām, kuras ir bioloģiskās daudzveidības apsaimniekošanas plānošanā 
nozīmīgas. Tajā pašā laikā, lai labāk saprastu analītisko pieeju iespējas un ierobežojumus, 
ir vērts izmēģināt ar dažādām sugām.

Izpratnes būvēšanai par sugu izplatības modelēšanu un kvantitatīvo ekoloģiju, iepazīstieties 
ar šī repozitorija pamata aprakstā ieteikto literatūru un to papildieniet ar aktuālajām publikācijām.


## Uzdevums

Pildot uzdevumu, domājiet arī par desmito un vienpadsmito uzdevumiem.

1. Iepazīstieties ar projekta sanāksmju materiāliem (direktorija "Sanaksmes"), ja 
tajās nepiedalījāties, un direktorijā "WP1" esošajiem uzdevumu (Task1.1, Task1.2 
un Task1.3) aprakstiem un sniegtajiem piemēriem.

2. Izvēlieties kādu sevi interējošo (vai projektā paredzēto) sugu grupu, no 
kuras izvēlaties vismaz 10 sugas. Izvēlaties gan specialiālistus, gan ģenerālistus. 
Uzturam komunikāciju savā starpā tā, lai jebkura viena suga būtu izvēlēta tikai 
vienu reizi.

3. Sagatavojiet Task1.1, Task1.2 un Task1.3 apkopojumus un aprakstus (bez novērojumu 
atlases). Uzturam komunikāciju (ar uzsvaru uz proaktīvu ierosināšanu, nevis tikai 
iztaujāšanu) par iespējamajām pazīmēm sugu savstarpējai svarošanai.

## Padomi

Sākot ar šo uzdevumu, mācamies arī strādāt kā komanda. Sazināmies, pārrunājam 
problēmas, nepieciešamības un iespējamos risinājumus, izmantojot diskusiju 
forumu vai tiekoties.